# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sig < Formula
  desc "CLI tool for checking IPs against CIDR blocks"
  homepage "https://clokwork.net/sig/"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/clok/sig/releases/download/v0.1.1/sig_0.1.1_darwin_arm64.tar.gz"
      sha256 "cc8e7ddc579a9350952f18cf19a5e43a3f94f928b4964bc2c26ecaffabd950c4"

      def install
        bin.install "sig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clok/sig/releases/download/v0.1.1/sig_0.1.1_darwin_amd64.tar.gz"
      sha256 "9f7632ee4a71d904503d75d68ee9ddd316d981514f5a8c9908c57947ab9407f6"

      def install
        bin.install "sig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/clok/sig/releases/download/v0.1.1/sig_0.1.1_linux_amd64.tar.gz"
      sha256 "235d935b60f939b6b4bb50c0af62f70732cc993ffb7fabc574b7d6825e8da1c4"

      def install
        bin.install "sig"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/clok/sig/releases/download/v0.1.1/sig_0.1.1_linux_armv6.tar.gz"
      sha256 "c7fd99dd8237b4021b9edfbf84d16657777723c3fbbe64583309a53d01f23386"

      def install
        bin.install "sig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clok/sig/releases/download/v0.1.1/sig_0.1.1_linux_arm64.tar.gz"
      sha256 "be97dfcbc7f4d671da9f93d408ec807decbb05053da9a1773e38a1979c92e08d"

      def install
        bin.install "sig"
      end
    end
  end

  test do
    system "#{bin}/sig --help"
  end
end
