# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sig < Formula
  desc "CLI tool for checking IPs against CIDR blocks"
  homepage "https://clokwork.net/sig/"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/clok/sig/releases/download/v1.1.1/sig_1.1.1_darwin_arm64.tar.gz"
      sha256 "c99a73e3f4d6bb17592246ad5021c393e88bc26c12b11171d6c8373c908deac8"

      def install
        bin.install "sig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clok/sig/releases/download/v1.1.1/sig_1.1.1_darwin_amd64.tar.gz"
      sha256 "e790f0f722cb2f25df6628a65232e8c365d3de144703eadbb854a6c4f15e1519"

      def install
        bin.install "sig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/clok/sig/releases/download/v1.1.1/sig_1.1.1_linux_armv6.tar.gz"
      sha256 "ace7cb23aa3c140b7bc05c517ed6953d01e0a126be25605393c68f711b08fd63"

      def install
        bin.install "sig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clok/sig/releases/download/v1.1.1/sig_1.1.1_linux_amd64.tar.gz"
      sha256 "d7fddfb276f1c0838c26d8ee445c335ffda4135297946702b887a7ce8b894202"

      def install
        bin.install "sig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clok/sig/releases/download/v1.1.1/sig_1.1.1_linux_arm64.tar.gz"
      sha256 "a035a23361cfeeb5bc8c73338cac46db9e26c0a101a6525425380ebc6355e112"

      def install
        bin.install "sig"
      end
    end
  end

  test do
    system "#{bin}/sig --help"
  end
end
