# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sig < Formula
  desc "CLI tool for checking IPs against CIDR blocks"
  homepage "https://clokwork.net/sig/"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clok/sig/releases/download/v1.1.0/sig_1.1.0_darwin_amd64.tar.gz"
      sha256 "1048225e29abd45d266f308f85dbe732111a386a718f98fb7693f30bba9017ba"

      def install
        bin.install "sig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clok/sig/releases/download/v1.1.0/sig_1.1.0_darwin_arm64.tar.gz"
      sha256 "1f5525be6b03c95b44838bef63411d519590b61915de69c279be41f949a1e606"

      def install
        bin.install "sig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/clok/sig/releases/download/v1.1.0/sig_1.1.0_linux_amd64.tar.gz"
      sha256 "2eb46100ea02fab957bf7ac9a638e324f560fc9cbd2c4f2a52ce66e280fa0425"

      def install
        bin.install "sig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clok/sig/releases/download/v1.1.0/sig_1.1.0_linux_arm64.tar.gz"
      sha256 "1615542960c62db47ed1e0f6435d837baf0312e19d45afab972ac5b7380a8e4e"

      def install
        bin.install "sig"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/clok/sig/releases/download/v1.1.0/sig_1.1.0_linux_armv6.tar.gz"
      sha256 "922057c8ea36154f4a844fea13bbe10974560884bd8a99ae92b496614274b9b7"

      def install
        bin.install "sig"
      end
    end
  end

  test do
    system "#{bin}/sig --help"
  end
end
